-- Xóa các bảng nếu chúng đã tồn tại
DROP TABLE IF EXISTS ratings CASCADE;
DROP TABLE IF EXISTS quotations CASCADE;
DROP TABLE IF EXISTS maintenance CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS black_list_token CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS roles CASCADE;

-- Tạo bảng roles
CREATE TABLE roles
(
    role_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(255) UNIQUE NOT NULL
);

-- Tạo bảng users
CREATE TABLE users
(
    user_id      BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username     VARCHAR(255),
    email        VARCHAR(255) UNIQUE NOT NULL,
    phone        VARCHAR(255),
    password     VARCHAR(255) NOT NULL,
    role_id      BIGINT NOT NULL,
    created_date DATE,
    otp_code     VARCHAR(255),
    dob          DATE,
    status       VARCHAR(255) NOT NULL,
    CONSTRAINT FK_USERS_ON_ROLE FOREIGN KEY (role_id) REFERENCES roles (role_id)
);

-- Tạo bảng orders
CREATE TABLE orders
(
    order_id       BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title          VARCHAR(255),
    order_number   VARCHAR(255),
    phone          VARCHAR(255),
    design_details VARCHAR(255),
    user_id        BIGINT,
    address        VARCHAR(255),
    service_type   SMALLINT,
    start_date     DATE,
    end_date       DATE,
    status         SMALLINT,
    CONSTRAINT FK_ORDERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id)
);

-- Tạo bảng maintenance
CREATE TABLE maintenance
(
    maintenanceid      BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title              VARCHAR(255),
    order_id           BIGINT UNIQUE,
    price              VARCHAR(255),
    user_id            BIGINT,
    construction_staff VARCHAR(255),
    start_date         DATE,
    end_date           DATE,
    content            VARCHAR(255),
    CONSTRAINT FK_MAINTENANCE_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (order_id),
    CONSTRAINT FK_MAINTENANCE_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id)
);

-- Tạo bảng quotations
CREATE TABLE quotations
(
    quotation_id        BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quotation_number    VARCHAR(255) NOT NULL,
    user_id             BIGINT NOT NULL,
    order_id            BIGINT UNIQUE,
    area_size           DOUBLE PRECISION NOT NULL,
    location            VARCHAR(255),
    design_details      VARCHAR(255),
    material_cost       DOUBLE PRECISION NOT NULL,
    labor_cost          DOUBLE PRECISION NOT NULL,
    transportation_cost DOUBLE PRECISION NOT NULL,
    total_cost          DOUBLE PRECISION NOT NULL,
    payment_method      VARCHAR(255) NOT NULL,
    quotation_date      DATE,
    status              VARCHAR(255),
    expiration_date     DATE NOT NULL,
    CONSTRAINT FK_QUOTATIONS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (order_id),
    CONSTRAINT FK_QUOTATIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id)
);

-- Tạo bảng ratings
CREATE TABLE ratings
(
    rating_id  BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id BIGINT,
    user_id    BIGINT,
    rating     INTEGER NOT NULL,
    feedback   VARCHAR(255),
    CONSTRAINT FK_RATINGS_ON_SERVICE FOREIGN KEY (service_id) REFERENCES orders (order_id),
    CONSTRAINT FK_RATINGS_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id)
);

-- Tạo bảng black_list_token
CREATE TABLE black_list_token
(
    id          BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token       VARCHAR(255) NOT NULL UNIQUE,
    expiry_date TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

-- Chèn dữ liệu vào bảng roles
INSERT INTO roles (name) VALUES
                             ('ROLE_ADMIN'),
                             ('ROLE_USER'),
                             ('ROLE_CONSULTING_STAFF'),
                             ('ROLE_DESIGN_STAFF'),
                             ('ROLE_CONSTRUCTION_STAFF'),
                             ('ROLE_MANAGER');
INSERT INTO orders (order_id, title, order_number, phone, design_details, user_id, address, service_type, start_date, end_date, status) VALUES
                                                                                                                                            (1, 'Thong tin don hang 1', 'XHSGGYU1', '0528661001', 'Thiết kế hồ cá diện tích 40m2...', 1, 'Ho Chi Minh', 1, '2024-11-10', '2024-11-20', 2),
                                                                                                                                            (2, 'Thong tin don hang 2', 'XHSGGYU2', '0528661002', 'Bảo trì hồ cá mini...', 2, 'Da Nang', 2, '2024-11-12', '2024-11-22', 1),
                                                                                                                                            (3, 'Thong tin don hang 3', 'XHSGGYU3', '0528661003', 'Sửa chữa hệ thống lọc...', 3, 'Hanoi', 3, '2024-11-15', '2024-11-25', 3),
                                                                                                                                            (4, 'Thong tin don hang 4', 'XHSGGYU4', '0528661004', 'Thiết kế hồ cá 30m2...', 1, 'Can Tho', 1, '2024-11-18', '2024-11-28', 2),
                                                                                                                                            (5, 'Thong tin don hang 5', 'XHSGGYU5', '0528661005', 'Bảo trì hồ cá lớn...', 2, 'Nha Trang', 2, '2024-11-20', '2024-11-30', 1),
                                                                                                                                            (6, 'Thong tin don hang 6', 'XHSGGYU6', '0528661006', 'Sửa chữa hệ thống đèn...', 3, 'Hue', 3, '2024-11-22', '2024-12-02', 2),
                                                                                                                                            (7, 'Thong tin don hang 7', 'XHSGGYU7', '0528661007', 'Thiết kế hồ cá diện tích 25m2...', 1, 'Ho Chi Minh', 1, '2024-11-25', '2024-12-05', 2),
                                                                                                                                            (8, 'Thong tin don hang 8', 'XHSGGYU8', '0528661008', 'Bảo trì hồ cá gia đình...', 2, 'Da Nang', 2, '2024-11-27', '2024-12-07', 3),
                                                                                                                                            (9, 'Thong tin don hang 9', 'XHSGGYU9', '0528661009', 'Sửa chữa lọc hồ...', 3, 'Hanoi', 3, '2024-11-30', '2024-12-10', 1),
                                                                                                                                            (10, 'Thong tin don hang 10', 'XHSGGY10', '0528661010', 'Thiết kế hồ cá sân thượng...', 1, 'Can Tho', 1, '2024-12-01', '2024-12-11', 4);
